version: '3'

services: 
  backend:
    image: alinaverse-backend
    build:
      context: .
      dockerfile: AlinaverseAPI/Dockerfile
    ports:
      - "80:80"
    depends_on: 
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5444:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql